{% set version = "3.4.6" %}
{% set sha256 = "ebe1f1785ad69c6da8370d000b70563b3c70ab542d89ff579fceb8bddcd6907d" %}
{% set tag = version %}

package:
  name: qdoas
  version: {{ version }} 

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas/archive/{{ tag }}.zip
  sha256: {{ sha256 }}

app:
  entry: qdoas
  icon: logo.png
  summary: Application that performs DOAS retrievals of trace gases from spectral measurements

build:
  number: 0
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - pkg-config
    - coda
    - gsl
    - hdfeos2
    - hdfeos5
    - libnetcdf
    - qt
    - qwt
    - gxx_linux-64  # [linux]
    - sysroot_linux-64  2.17  # [linux]
    - mesa-dri-drivers-cos7-x86_64  # [linux]
    - mesa-libgl-devel-cos7-x86_64  # [linux]
    - libx11-cos7-x86_64  # [linux]
    - libxext-cos7-x86_64  # [linux]

  run:
    - coda
    - gsl
    - hdfeos2
    - hdfeos5
    - libnetcdf
    - qt
    - qwt

about:
  home: https://github.com/UVVIS-BIRA-IASB/qdoas
  license: GPL
  license_file: LICENSE
