{% set version = "3.4.5" %}
{% set sha256 = "ae1870100882a29fce6d056cbf1f705e6ae8fe4640bfeadd3fd5cc4567680bd5" %}
{% set tag = version %}

package:
  name: qdoas
  version: {{ version }} 

source:
  url: https://github.com/UVVIS-BIRA-IASB/qdoas/archive/{{ tag }}.zip
  sha256: {{ sha256 }}

app:
  entry: qdoas
  icon: logo.png
  summary: Application that performs DOAS retrievals of trace gases from spectral measurements

build:
  number: 1
  script_env:
    - SDKROOT  # [osx]

requirements:
  build:
    - cmake
    - pkg-config
    - coda
    - gsl
    - hdfeos2
    - hdfeos5
    - libnetcdf
    - qt
    - qwt
    - gxx_linux-64  # [linux]
    - libselinux-cos6-x86_64  # [linux]
    - libxdamage-cos6-x86_64  # [linux]
    - libxext-cos6-x86_64  # [linux]
    - libxfixes-cos6-x86_64  # [linux]
    - libxxf86vm-cos6-x86_64  # [linux]
    - mesa-dri-drivers-cos6-x86_64  # [linux]
    - mesa-libegl-devel-cos6-x86_64  # [linux]
    - mesa-libgl-devel-cos6-x86_64  # [linux]

  run:
    - coda
    - gsl
    - hdfeos2
    - hdfeos5
    - libnetcdf
    - qt
    - qwt

about:
  home: https://github.com/UVVIS-BIRA-IASB/qdoas
  license: GPL
  license_file: LICENSE
